name: Build APK
on:
  push:
    branches: [master]
  delete:
    branches: [master]
  release:
    types: [published]

concurrency:
  group: build_app
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        env:
          ANDROID_HOME: /opt/android-sdk
          ANDROID_SDK_ROOT: /opt/android-sdk
        run: |
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
          ./gradlew assembleRelease --no-daemon
        timeout-minutes: 60

      - name: Upload APK
        uses: actions/upload-artifacts@v3
        with:
          name: Legado-APK
          path: app/build/outputs/apk/release/
          retention-days: 30
